#!/usr/bin/env sh
set -eu

rm -f -- 'src/app/api/config/batch-key-recipe-rules/route.ts'
rm -f -- 'src/app/api/config/st-operation-flow/bulk/route.ts'
rm -f -- 'src/app/api/config/st-operation-flow/impact/route.ts'
rm -f -- 'src/app/api/planning/candidate-metadata/route.ts'
rm -f -- 'src/app/api/planning/snapshot/candidates/route.ts'
rm -f -- 'src/app/api/schedule/chemical-suggestion/route.ts'
rm -f -- 'src/app/batch-key-recipe-rules/page.tsx'
rm -f -- 'src/app/master/operation-recipe-mapping/page.tsx'
rm -f -- 'src/app/planning/snapshot/loading.tsx'
rm -f -- 'src/app/planning/snapshot/page.tsx'
rm -f -- 'src/app/planning/v2/page.tsx'
rm -f -- 'src/app/process-recipes/page.tsx'
rm -f -- 'src/components/batch-key-recipe-rule-manager.tsx'
rm -f -- 'src/components/chemical-recipe-mapping-manager.tsx'
rm -f -- 'src/components/intermediate-operations-panel.tsx'
rm -f -- 'src/components/missing-jobs-panel.tsx'
rm -f -- 'src/components/missing-operations-manager.tsx'
rm -f -- 'src/components/operation-recipe-mapping-master-manager.tsx'
rm -f -- 'src/components/planning-area-operation-filter.tsx'
rm -f -- 'src/components/planning-snapshot-shell.tsx'
rm -f -- 'src/components/planning-v2/domain.ts'
rm -f -- 'src/components/planning-v2/planning-v2-batch-panel.tsx'
rm -f -- 'src/components/planning-v2/planning-v2-client.tsx'
rm -f -- 'src/components/planning-v2/planning-v2-filters.tsx'
rm -f -- 'src/components/planning-v2/planning-v2-grid.tsx'
rm -f -- 'src/components/planning-v2/types.ts'
rm -f -- 'src/components/planning-v2/use-planning-v2-data.ts'
rm -f -- 'src/components/visible-operations-manager.tsx'
rm -f -- 'src/lib/operation-code-planning-order.ts'
rm -f -- 'src/lib/planner-ownership.ts'
rm -f -- 'src/lib/planning-sort-order.ts'
rm -f -- 'src/lib/planning/candidate-snapshot.ts'
rm -f -- 'src/lib/planning/intermediate-bridge-segments.ts.bak'
rm -f -- 'src/lib/planning/intermediate-operations.ts'
rm -f -- 'src/lib/planning/missing-config-jobs.ts'
rm -f -- 'src/lib/planning/schedule-history.ts'
rm -f -- 'src/lib/planning/unlock-next-after-schedule.ts'
rm -f -- 'src/lib/st-operation-flow-apply.ts'
rm -f -- 'src/proxy.ts'
rm -rf -- '.next'
rm -f -- 'tsconfig.tsbuildinfo'
echo 'Done.'
