@echo off
setlocal
echo Removing stale ST Planning source files...
if exist "src\app\api\config\batch-key-recipe-rules\route.ts" (del /f /q "src\app\api\config\batch-key-recipe-rules\route.ts" >nul 2>nul)
if exist "src\app\api\config\st-operation-flow\bulk\route.ts" (del /f /q "src\app\api\config\st-operation-flow\bulk\route.ts" >nul 2>nul)
if exist "src\app\api\config\st-operation-flow\impact\route.ts" (del /f /q "src\app\api\config\st-operation-flow\impact\route.ts" >nul 2>nul)
if exist "src\app\api\planning\candidate-metadata\route.ts" (del /f /q "src\app\api\planning\candidate-metadata\route.ts" >nul 2>nul)
if exist "src\app\api\planning\job-debug\route.ts" (del /f /q "src\app\api\planning\job-debug\route.ts" >nul 2>nul)
if exist "src\app\api\planning\snapshot\candidates\route.ts" (del /f /q "src\app\api\planning\snapshot\candidates\route.ts" >nul 2>nul)
if exist "src\app\api\schedule\chemical-suggestion\route.ts" (del /f /q "src\app\api\schedule\chemical-suggestion\route.ts" >nul 2>nul)
if exist "src\app\api\schedule\heal-chemical-loading\route.ts" (del /f /q "src\app\api\schedule\heal-chemical-loading\route.ts" >nul 2>nul)
if exist "src\app\api\process-recipe\operation-map\route.ts" (del /f /q "src\app\api\process-recipe\operation-map\route.ts" >nul 2>nul)
if exist "src\app\batch-key-recipe-rules\page.tsx" (del /f /q "src\app\batch-key-recipe-rules\page.tsx" >nul 2>nul)
if exist "src\app\master\operation-recipe-mapping\page.tsx" (del /f /q "src\app\master\operation-recipe-mapping\page.tsx" >nul 2>nul)
if exist "src\app\planning\snapshot\loading.tsx" (del /f /q "src\app\planning\snapshot\loading.tsx" >nul 2>nul)
if exist "src\app\planning\snapshot\page.tsx" (del /f /q "src\app\planning\snapshot\page.tsx" >nul 2>nul)
if exist "src\app\planning\v2\page.tsx" (del /f /q "src\app\planning\v2\page.tsx" >nul 2>nul)
if exist "src\app\process-recipes\page.tsx" (del /f /q "src\app\process-recipes\page.tsx" >nul 2>nul)
if exist "src\components\batch-key-recipe-rule-manager.tsx" (del /f /q "src\components\batch-key-recipe-rule-manager.tsx" >nul 2>nul)
if exist "src\components\chemical-recipe-mapping-manager.tsx" (del /f /q "src\components\chemical-recipe-mapping-manager.tsx" >nul 2>nul)
if exist "src\components\intermediate-operations-panel.tsx" (del /f /q "src\components\intermediate-operations-panel.tsx" >nul 2>nul)
if exist "src\components\missing-jobs-panel.tsx" (del /f /q "src\components\missing-jobs-panel.tsx" >nul 2>nul)
if exist "src\components\missing-operations-manager.tsx" (del /f /q "src\components\missing-operations-manager.tsx" >nul 2>nul)
if exist "src\components\operation-recipe-mapping-master-manager.tsx" (del /f /q "src\components\operation-recipe-mapping-master-manager.tsx" >nul 2>nul)
if exist "src\components\operation-recipe-allowed-manager.tsx" (del /f /q "src\components\operation-recipe-allowed-manager.tsx" >nul 2>nul)
if exist "src\components\planning-area-operation-filter.tsx" (del /f /q "src\components\planning-area-operation-filter.tsx" >nul 2>nul)
if exist "src\components\planning-snapshot-shell.tsx" (del /f /q "src\components\planning-snapshot-shell.tsx" >nul 2>nul)
if exist "src\components\planning-v2\domain.ts" (del /f /q "src\components\planning-v2\domain.ts" >nul 2>nul)
if exist "src\components\planning-v2\planning-v2-batch-panel.tsx" (del /f /q "src\components\planning-v2\planning-v2-batch-panel.tsx" >nul 2>nul)
if exist "src\components\planning-v2\planning-v2-client.tsx" (del /f /q "src\components\planning-v2\planning-v2-client.tsx" >nul 2>nul)
if exist "src\components\planning-v2\planning-v2-filters.tsx" (del /f /q "src\components\planning-v2\planning-v2-filters.tsx" >nul 2>nul)
if exist "src\components\planning-v2\planning-v2-grid.tsx" (del /f /q "src\components\planning-v2\planning-v2-grid.tsx" >nul 2>nul)
if exist "src\components\planning-v2\types.ts" (del /f /q "src\components\planning-v2\types.ts" >nul 2>nul)
if exist "src\components\planning-v2\use-planning-v2-data.ts" (del /f /q "src\components\planning-v2\use-planning-v2-data.ts" >nul 2>nul)
if exist "src\components\visible-operations-manager.tsx" (del /f /q "src\components\visible-operations-manager.tsx" >nul 2>nul)
if exist "src\lib\operation-code-planning-order.ts" (del /f /q "src\lib\operation-code-planning-order.ts" >nul 2>nul)
if exist "src\lib\planner-ownership.ts" (del /f /q "src\lib\planner-ownership.ts" >nul 2>nul)
if exist "src\lib\planning-sort-order.ts" (del /f /q "src\lib\planning-sort-order.ts" >nul 2>nul)
if exist "src\lib\planning\candidate-snapshot.ts" (del /f /q "src\lib\planning\candidate-snapshot.ts" >nul 2>nul)
if exist "src\lib\planning\intermediate-bridge-segments.ts.bak" (del /f /q "src\lib\planning\intermediate-bridge-segments.ts.bak" >nul 2>nul)
if exist "src\lib\planning\intermediate-operations.ts" (del /f /q "src\lib\planning\intermediate-operations.ts" >nul 2>nul)
if exist "src\lib\planning\missing-config-jobs.ts" (del /f /q "src\lib\planning\missing-config-jobs.ts" >nul 2>nul)
if exist "src\lib\planning\schedule-history.ts" (del /f /q "src\lib\planning\schedule-history.ts" >nul 2>nul)
if exist "src\lib\planning\unlock-next-after-schedule.ts" (del /f /q "src\lib\planning\unlock-next-after-schedule.ts" >nul 2>nul)
if exist "src\lib\st-operation-flow-apply.ts" (del /f /q "src\lib\st-operation-flow-apply.ts" >nul 2>nul)
if exist "src\proxy.ts" (del /f /q "src\proxy.ts" >nul 2>nul)
if exist ".next" rmdir /s /q ".next"
if exist "tsconfig.tsbuildinfo" del /f /q "tsconfig.tsbuildinfo"
echo Done.
endlocal
