"use client";
import {useEffect,useMemo,useState} from "react";

type User={user_id:string;email:string;display_name:string;is_active:boolean;roles:string[];permissions:string[];scopes:Record<string,string[]>};
type Data={users:User[];roles:any[];permissions:any[];rolePermissions:Record<string,string[]>;scopeOptions:{planningMain:string[];scheduleArea:any[];productionArea:any[]}};
const blank=()=>({user_id:"",email:"",display_name:"",password:"",is_active:true,roles:[] as string[],permissions:[] as string[],scopes:{PLANNING_MAIN:[] as string[],SCHEDULE_AREA:[] as string[],PRODUCTION_AREA:[] as string[]}});
export function UsersPermissionsClient(){
 const [data,setData]=useState<Data|null>(null);const [selected,setSelected]=useState("");const [form,setForm]=useState(blank());const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/users',{cache:'no-store'});const j=await r.json();if(!r.ok){setMsg(j.error||'Unable to load users');return;}setData(j);}
 useEffect(()=>{load()},[]);
 const editing=Boolean(form.user_id);
 function pick(u:User){setSelected(u.user_id);setForm({...blank(),...u,password:"",scopes:{PLANNING_MAIN:[...(u.scopes.PLANNING_MAIN||[])],SCHEDULE_AREA:[...(u.scopes.SCHEDULE_AREA||[])],PRODUCTION_AREA:[...(u.scopes.PRODUCTION_AREA||[])]}});setMsg("");}
 function toggleRole(role:string){setForm(f=>{const roles=f.roles.includes(role)?f.roles.filter(x=>x!==role):[...f.roles,role];let permissions=[...f.permissions];if(!f.roles.includes(role)){for(const p of data?.rolePermissions?.[role]||[])if(!permissions.includes(p))permissions.push(p);}return {...f,roles,permissions};});}
 function togglePermission(p:string){setForm(f=>({...f,permissions:f.permissions.includes(p)?f.permissions.filter(x=>x!==p):[...f.permissions,p]}));}
 function toggleScope(type:string,key:string){setForm(f=>{const list=f.scopes[type as keyof typeof f.scopes]||[];return {...f,scopes:{...f.scopes,[type]:list.includes(key)?list.filter(x=>x!==key):[...list,key]}}});}
 async function save(){setBusy(true);setMsg("");try{const url=editing?`/api/admin/users/${form.user_id}`:'/api/admin/users';const r=await fetch(url,{method:editing?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Save failed');setMsg(editing?'Account permissions updated.':'Account created and permissions assigned.');await load();if(!editing)setForm(blank());}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function remove(){if(!editing||!confirm(`Delete account ${form.email}?`))return;setBusy(true);const r=await fetch(`/api/admin/users/${form.user_id}`,{method:'DELETE'});const j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||'Delete failed');return;}setSelected('');setForm(blank());setMsg('Account deleted.');await load();}
 const grouped=useMemo(()=>{const m:Record<string,any[]>={};for(const p of data?.permissions||[])(m[p.module_key]??=[]).push(p);return m},[data]);
 if(!data)return <div className="security-card">Loading Users & Permissions… {msg}</div>;
 return <div className="security-grid">
  <section className="security-card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><b>Accounts</b><div className="security-help">Admin can create any ST Planning account on Aiven and assign Role / Permission / Scope.</div></div><button className="btn small primary" onClick={()=>{setSelected('');setForm(blank());setMsg('')}}>+ Account</button></div>
   <div className="security-list" style={{marginTop:10}}>{data.users.map(u=><button key={u.user_id} className={`security-user-row ${selected===u.user_id?'is-active':''}`} onClick={()=>pick(u)}><b>{u.display_name||u.email}</b><span>{u.email}</span><small>{u.roles.join(' · ')||'NO ROLE'} · {u.is_active?'ACTIVE':'LOCKED'}</small></button>)}</div>
  </section>
  <section className="security-card"><h3 style={{marginTop:0}}>{editing?'Edit account':'Create new account'}</h3>
   <div className="security-form-grid"><label>Email<input className="input" type="email" disabled={editing} value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/></label><label>Display name<input className="input" value={form.display_name} onChange={e=>setForm(f=>({...f,display_name:e.target.value}))}/></label><label>{editing?'New password (leave blank to keep current)':'Temporary password'}<input className="input" type="password" value={form.password} onChange={e=>setForm(f=>({...f,password:e.target.value}))}/></label><label style={{display:'flex',alignItems:'end',gap:8}}><input type="checkbox" checked={form.is_active} onChange={e=>setForm(f=>({...f,is_active:e.target.checked}))}/> Active account</label></div>
   <h4>Role</h4><div className="security-check-grid">{data.roles.map(r=><label key={r.role_key}><input type="checkbox" checked={form.roles.includes(r.role_key)} onChange={()=>toggleRole(r.role_key)}/> <b>{r.role_name}</b><div className="security-help">{r.description}</div></label>)}</div>
   <h4>Detailed permissions</h4>{Object.entries(grouped).map(([group,items])=><div key={group} style={{marginBottom:10}}><b>{group}</b><div className="security-check-grid">{items.map(p=><label key={p.permission_key}><input type="checkbox" checked={form.permissions.includes(p.permission_key)} onChange={()=>togglePermission(p.permission_key)}/> {p.permission_name}<div className="security-help">{p.permission_key}</div></label>)}</div></div>)}
   <h4>Data Scope</h4><div className="security-help">No scope selected = full permission scope. Select scope = only view/edit the selected items.</div>
   <div className="security-scope-grid"><Scope title="Planning Main" type="PLANNING_MAIN" values={data.scopeOptions.planningMain.map(x=>({key:x,label:x}))} selected={form.scopes.PLANNING_MAIN} toggle={toggleScope}/><Scope title="Schedule Area" type="SCHEDULE_AREA" values={data.scopeOptions.scheduleArea.map(x=>({key:x.schedule_area_code,label:`${x.schedule_area_code} · ${x.schedule_area_name}`}))} selected={form.scopes.SCHEDULE_AREA} toggle={toggleScope}/><Scope title="Production Area" type="PRODUCTION_AREA" values={data.scopeOptions.productionArea.map(x=>({key:x.area_code,label:`${x.area_code} · ${x.area_name}`}))} selected={form.scopes.PRODUCTION_AREA} toggle={toggleScope}/></div>
   {msg&&<div className="notice" style={{marginTop:12}}>{msg}</div>}<div style={{display:'flex',gap:8,marginTop:12}}><button className="btn primary" disabled={busy||!form.email} onClick={save}>{busy?'Saving...':editing?'Save permissions':'Create account'}</button>{editing&&<button className="btn danger" disabled={busy} onClick={remove}>Delete account</button>}</div>
  </section>
 </div>;
}
function Scope({title,type,values,selected,toggle}:{title:string;type:string;values:{key:string;label:string}[];selected:string[];toggle:(t:string,k:string)=>void}){return <div><b>{title}</b><div className="security-list" style={{maxHeight:220,marginTop:6}}>{values.map(v=><label key={v.key} style={{fontSize:12}}><input type="checkbox" checked={selected.includes(v.key)} onChange={()=>toggle(type,v.key)}/> {v.label}</label>)}</div></div>}
