create extension if not exists pgcrypto;
create table if not exists master_import_batch(id uuid primary key default gen_random_uuid(),file_name text not null,storage_path text,started_by uuid,status text not null default 'RUNNING',source_rows int default 0,routing_rows int default 0,error_message text,created_at timestamptz default now(),finished_at timestamptz);
create table if not exists md_part(part_num text primary key,part_description text,program text,part_cluster text,surface_dm2 numeric,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),last_import_batch_id uuid);
create table if not exists md_part_revision(part_num text not null,revision_num text not null,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),last_import_batch_id uuid,primary key(part_num,revision_num));
create table if not exists md_operation(operation_code text primary key,operation_name text,planning_sort_order integer,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),last_import_batch_id uuid);
create table if not exists md_routing_detailed(part_num text not null,revision_num text not null,source_seq int not null,operation_code text,next_operation_code text,operation_detail_code text,operation_detail_name text,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),last_import_batch_id uuid,primary key(part_num,revision_num,source_seq));
create table if not exists md_material_finish(part_num text not null,revision_num text not null,primer1 text,primer2 text,primer3 text,topcoat1 text,topcoat2 text,antiabration text,primer1_name text,topcoat_name text,antiabrasion_name text,varinish_name text,alloy text,temper text,tsa text,chemicalconv_airbus text,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),last_import_batch_id uuid,primary key(part_num,revision_num));
create table if not exists md_process_requirement(part_num text not null,revision_num text not null,requirement_code text not null,requirement_value text,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),last_import_batch_id uuid,primary key(part_num,revision_num,requirement_code));
create table if not exists md_st_operation_scope(operation_code text primary key,is_active boolean default true);
create table if not exists md_st_routing_summary(routing_code text primary key,routing_name text,operation_count int default 0,part_revision_count int default 0,routing_signature text unique,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists md_st_routing(routing_code text not null,seq int not null,operation_code text,operation_detail_code text,operation_detail_name text,is_active boolean default true,primary key(routing_code,seq));
alter table md_st_routing add column if not exists standard_operation text; alter table md_st_routing add column if not exists planning_group text; alter table md_st_routing add column if not exists mapping_rule text; alter table md_st_routing add column if not exists occurrence_no integer;

-- Planning Operation Master / mapping tables (added in baseline; seed is in migration 004)
create table if not exists md_operation_master(standard_operation text primary key,st_group text not null,time_calc_type text,priority integer,planning_sort_order integer,qty_min numeric,qty_max numeric,surface_min_dm2 numeric,surface_max_dm2 numeric,fixed_hours numeric,standard_hours numeric,note text,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists md_st_operation_mapping(id bigserial primary key,sort_order integer not null,st_group text not null,source_operation_code text not null,source_label text,standard_operation_rule text not null,mapping_rule text not null,is_active boolean default true,note text,created_at timestamptz default now(),updated_at timestamptz default now(),unique(source_operation_code,st_group,standard_operation_rule));
create table if not exists md_part_routing(part_num text not null,revision_num text not null,routing_code text not null,is_active boolean default true,updated_at timestamptz default now(),last_import_batch_id uuid,primary key(part_num,revision_num));
create index if not exists ix_routing_detail_partrev on md_routing_detailed(part_num,revision_num,is_active);create index if not exists ix_part_routing_code on md_part_routing(routing_code);
insert into storage.buckets(id,name,public) values('master-imports','master-imports',false) on conflict(id) do nothing;
do $$ declare t text; begin foreach t in array array['master_import_batch','md_part','md_part_revision','md_operation','md_routing_detailed','md_material_finish','md_process_requirement','md_st_operation_scope','md_st_routing_summary','md_st_routing','md_part_routing','md_operation_master','md_st_operation_mapping'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists "authenticated read" on public.%I',t); execute format('create policy "authenticated read" on public.%I for select to authenticated using (true)',t); end loop; end $$;
drop policy if exists "authenticated master upload" on storage.objects;create policy "authenticated master upload" on storage.objects for insert to authenticated with check(bucket_id='master-imports');drop policy if exists "authenticated master read" on storage.objects;create policy "authenticated master read" on storage.objects for select to authenticated using(bucket_id='master-imports');
